import './globals.css'
import Navbar from './ui/navbar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en' data-theme='lofi'>
      <body className='flex flex-col min-h-screen'>
        <Navbar />
        <div className='max-w-7xl flex flex-col flex-1 mx-auto w-full'>
          {children}
        </div>
        <footer className='footer footer-center py-12'>
          <aside>
            <p>Open App Note</p>
          </aside>
        </footer>
      </body>
    </html>
  )
}
