import './globals.css'
import Navbar from './ui/navbar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en' data-theme='lofi'>
      <body>
        <Navbar />
        {children}
      </body>
      <footer className='footer footer-center p-6'>
        <aside>
          <p>Open App Note</p>
        </aside>
      </footer>
    </html>
  )
}
